imports:
    - { resource: finite_state.yml }
    - { resource: rest.yml } # you could omit this if you don't want rest functionality

simple_purchase_process:
    leaphly_api_host:  %leaphly_api_host%
    leaphly_api_port:  %leaphly_api_port%
