framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# stub for http client.
parameters:
    acme.demo.http_client.class: Acme\SimplePurchaseProcessBundle\Tests\Mock\MockedHttpClient